/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package logica;

/**
 *
 * @author dark
 */
public class EstadisticaVital_defuncion extends FilaEstadisticaVital{

    public EstadisticaVital_defuncion(String index, String numero_certificado, String departamento, String municipio, String area_de_defuncion, String inspeccion_corregimiento_o_caserio_defuncion, String sitio_defuncion, String codigo_institucion, String nombre_institucion, String tipo_defuncion, String fecha_defuncion, String hora_defuncion, String sexo_fallecido, String nombres_fallecido, String apellidos_fallecido, String tipo_documento_fallecido, String numero_documento_fallecido, String fecha_nacimiento_fallecido, String estado_conyugal_fallecido, String edad_fallecido, String nivel_educativo, String ultimo_year_aprovado, String ocupacion, String pertencia_etnica, String grupo_indigena, String pais_residencia, String departamento_residencia, String municipio_residencia, String localidad, String barrio, String direccion, String centro_poblado, String rural_disperso, String regimen_seguridad, String tipo_administradora, String nombre_administradora, String probable_manera_muerte, String relacion_muerte_parto, String tipo_parto, String multiplicidad, String tiempo_gestacion, String peso_feto, String tipo_documento_madre, String numero_documento_madre, String nombre_madre, String apellidos_madre, String edad_madre, String hijos_nacidos_vivos, String hijos_nacidos_muertos, String estado_conyugal_madre, String nivel_educativo_madre, String ultimo_year_aprobado_madre, String embarazada_cuandno_fallecio, String embarazada_ultimas_6_semanas, String embarazada_ultimas_12_meses, String tipo_muerte_violenta, String descripcion_muerte_violenta, String departamento_muerte_violenta, String municipio_muerte_violenta, String direccion_muerte_violenta, String mecanismo_1, String mecanismo_2, String mecanismo_3, String mecanismo_4, String recibio_asistencia_medica, String causa_directa, String causa_antesedentes_b, String causa_antesedentes_c, String causa_antesedentes_d, String estado_patologico, String causa_basica, String muerte_sin_certificacion_medica, String nombres_y_apellidos_certificador, String numero_documento_certificador, String tipo_profesion, String registro_profesional, String departamento_expedicion, String municipio_expedicion, String fecha_expedicion, String estado_certificado) {
        super(index, numero_certificado, departamento, municipio, area_de_defuncion, inspeccion_corregimiento_o_caserio_defuncion, sitio_defuncion, codigo_institucion, nombre_institucion, tipo_defuncion, fecha_defuncion, hora_defuncion, sexo_fallecido, nombres_fallecido, apellidos_fallecido, tipo_documento_fallecido, numero_documento_fallecido, fecha_nacimiento_fallecido, estado_conyugal_fallecido, edad_fallecido, nivel_educativo, ultimo_year_aprovado, ocupacion, pertencia_etnica, grupo_indigena, pais_residencia, departamento_residencia, municipio_residencia, localidad, barrio, direccion, centro_poblado, rural_disperso, regimen_seguridad, tipo_administradora, nombre_administradora, probable_manera_muerte, relacion_muerte_parto, tipo_parto, multiplicidad, tiempo_gestacion, peso_feto, tipo_documento_madre, numero_documento_madre, nombre_madre, apellidos_madre, edad_madre, hijos_nacidos_vivos, hijos_nacidos_muertos, estado_conyugal_madre, nivel_educativo_madre, ultimo_year_aprobado_madre, embarazada_cuandno_fallecio, embarazada_ultimas_6_semanas, embarazada_ultimas_12_meses, tipo_muerte_violenta, descripcion_muerte_violenta, departamento_muerte_violenta, municipio_muerte_violenta, direccion_muerte_violenta, mecanismo_1, mecanismo_2, mecanismo_3, mecanismo_4, recibio_asistencia_medica, causa_directa, causa_antesedentes_b, causa_antesedentes_c, causa_antesedentes_d, estado_patologico, causa_basica, muerte_sin_certificacion_medica, nombres_y_apellidos_certificador, numero_documento_certificador, tipo_profesion, registro_profesional, departamento_expedicion, municipio_expedicion, fecha_expedicion, estado_certificado);
    }

    public EstadisticaVital_defuncion(String index, String numero_certificado, String departamento, String municipio, String area_de_defuncion, String inspeccion_corregimiento_o_caserio_defuncion, String sitio_defuncion, String codigo_institucion, String nombre_institucion, String tipo_defuncion, String fecha_defuncion, String hora_defuncion, String sexo_fallecido, String nombres_fallecido, String apellidos_fallecido, String tipo_documento_fallecido, String numero_documento_fallecido, String fecha_nacimiento_fallecido, String estado_conyugal_fallecido, String edad_fallecido, String nivel_educativo, String ultimo_year_aprovado, String ocupacion, String pertencia_etnica, String grupo_indigena, String pais_residencia, String departamento_residencia, String municipio_residencia, String localidad, String barrio, String direccion, String centro_poblado, String rural_disperso, String regimen_seguridad, String tipo_administradora, String nombre_administradora, String probable_manera_muerte, String expedido_por, String relacion_muerte_parto, String tipo_parto, String multiplicidad, String tiempo_gestacion, String peso_feto, String tipo_documento_madre, String numero_documento_madre, String nombre_madre, String apellidos_madre, String edad_madre, String hijos_nacidos_vivos, String hijos_nacidos_muertos, String estado_conyugal_madre, String nivel_educativo_madre, String ultimo_year_aprobado_madre, String embarazada_cuandno_fallecio, String embarazada_ultimas_6_semanas, String embarazada_ultimas_12_meses, String tipo_muerte_violenta, String descripcion_muerte_violenta, String departamento_muerte_violenta, String municipio_muerte_violenta, String direccion_muerte_violenta, String mecanismo_1, String mecanismo_2, String mecanismo_3, String mecanismo_4, String recibio_asistencia_medica, String causa_directa, String causa_antesedentes_b, String causa_antesedentes_c, String causa_antesedentes_d, String estado_patologico, String causa_basica, String muerte_sin_certificacion_medica, String nombres_y_apellidos_certificador, String numero_documento_certificador, String tipo_profesion, String registro_profesional, String departamento_expedicion, String municipio_expedicion, String fecha_expedicion, String estado_certificado) {
        super(index, numero_certificado, departamento, municipio, area_de_defuncion, inspeccion_corregimiento_o_caserio_defuncion, sitio_defuncion, codigo_institucion, nombre_institucion, tipo_defuncion, fecha_defuncion, hora_defuncion, sexo_fallecido, nombres_fallecido, apellidos_fallecido, tipo_documento_fallecido, numero_documento_fallecido, fecha_nacimiento_fallecido, estado_conyugal_fallecido, edad_fallecido, nivel_educativo, ultimo_year_aprovado, ocupacion, pertencia_etnica, grupo_indigena, pais_residencia, departamento_residencia, municipio_residencia, localidad, barrio, direccion, centro_poblado, rural_disperso, regimen_seguridad, tipo_administradora, nombre_administradora, probable_manera_muerte, expedido_por, relacion_muerte_parto, tipo_parto, multiplicidad, tiempo_gestacion, peso_feto, tipo_documento_madre, numero_documento_madre, nombre_madre, apellidos_madre, edad_madre, hijos_nacidos_vivos, hijos_nacidos_muertos, estado_conyugal_madre, nivel_educativo_madre, ultimo_year_aprobado_madre, embarazada_cuandno_fallecio, embarazada_ultimas_6_semanas, embarazada_ultimas_12_meses, tipo_muerte_violenta, descripcion_muerte_violenta, departamento_muerte_violenta, municipio_muerte_violenta, direccion_muerte_violenta, mecanismo_1, mecanismo_2, mecanismo_3, mecanismo_4, recibio_asistencia_medica, causa_directa, causa_antesedentes_b, causa_antesedentes_c, causa_antesedentes_d, estado_patologico, causa_basica, muerte_sin_certificacion_medica, nombres_y_apellidos_certificador, numero_documento_certificador, tipo_profesion, registro_profesional, departamento_expedicion, municipio_expedicion, fecha_expedicion, estado_certificado);
    }

    public EstadisticaVital_defuncion(String index, String numero_certificado, String departamento, String municipio, String area_de_defuncion, String inspeccion_corregimiento_o_caserio_defuncion, String sitio_defuncion, String codigo_institucion, String nombre_institucion, String tipo_defuncion, String fecha_defuncion, String hora_defuncion, String sexo_fallecido, String nombres_fallecido, String apellidos_fallecido, String tipo_documento_fallecido, String numero_documento_fallecido, String fecha_nacimiento_fallecido, String estado_conyugal_fallecido, String edad_fallecido, String nivel_educativo, String ultimo_year_aprovado, String ocupacion, String pertencia_etnica, String grupo_indigena, String pais_residencia, String departamento_residencia, String municipio_residencia, String area_residencia, String localidad, String barrio, String direccion, String centro_poblado, String rural_disperso, String regimen_seguridad, String tipo_administradora, String nombre_administradora, String probable_manera_muerte, String expedido_por, String relacion_muerte_parto, String tipo_parto, String multiplicidad, String tiempo_gestacion, String peso_feto, String tipo_documento_madre, String numero_documento_madre, String nombre_madre, String apellidos_madre, String edad_madre, String hijos_nacidos_vivos, String hijos_nacidos_muertos, String estado_conyugal_madre, String nivel_educativo_madre, String ultimo_year_aprobado_madre, String embarazada_cuandno_fallecio, String embarazada_ultimas_6_semanas, String embarazada_ultimas_12_meses, String tipo_muerte_violenta, String descripcion_muerte_violenta, String departamento_muerte_violenta, String municipio_muerte_violenta, String direccion_muerte_violenta, String mecanismo_1, String mecanismo_2, String mecanismo_3, String mecanismo_4, String recibio_asistencia_medica, String causa_directa, String causa_antesedentes_b, String causa_antesedentes_c, String causa_antesedentes_d, String estado_patologico, String causa_basica, String muerte_sin_certificacion_medica, String nombres_y_apellidos_certificador, String tipo_documento_certificador, String numero_documento_certificador, String tipo_profesion, String registro_profesional, String departamento_expedicion, String municipio_expedicion, String fecha_expedicion, String estado_certificado) {
        super(index, numero_certificado, departamento, municipio, area_de_defuncion, inspeccion_corregimiento_o_caserio_defuncion, sitio_defuncion, codigo_institucion, nombre_institucion, tipo_defuncion, fecha_defuncion, hora_defuncion, sexo_fallecido, nombres_fallecido, apellidos_fallecido, tipo_documento_fallecido, numero_documento_fallecido, fecha_nacimiento_fallecido, estado_conyugal_fallecido, edad_fallecido, nivel_educativo, ultimo_year_aprovado, ocupacion, pertencia_etnica, grupo_indigena, pais_residencia, departamento_residencia, municipio_residencia, area_residencia, localidad, barrio, direccion, centro_poblado, rural_disperso, regimen_seguridad, tipo_administradora, nombre_administradora, probable_manera_muerte, expedido_por, relacion_muerte_parto, tipo_parto, multiplicidad, tiempo_gestacion, peso_feto, tipo_documento_madre, numero_documento_madre, nombre_madre, apellidos_madre, edad_madre, hijos_nacidos_vivos, hijos_nacidos_muertos, estado_conyugal_madre, nivel_educativo_madre, ultimo_year_aprobado_madre, embarazada_cuandno_fallecio, embarazada_ultimas_6_semanas, embarazada_ultimas_12_meses, tipo_muerte_violenta, descripcion_muerte_violenta, departamento_muerte_violenta, municipio_muerte_violenta, direccion_muerte_violenta, mecanismo_1, mecanismo_2, mecanismo_3, mecanismo_4, recibio_asistencia_medica, causa_directa, causa_antesedentes_b, causa_antesedentes_c, causa_antesedentes_d, estado_patologico, causa_basica, muerte_sin_certificacion_medica, nombres_y_apellidos_certificador, tipo_documento_certificador, numero_documento_certificador, tipo_profesion, registro_profesional, departamento_expedicion, municipio_expedicion, fecha_expedicion, estado_certificado);
    }
    
    
    

    
    
}
